service: supercats

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    # this is necessary to avoid cross-platform build issues
    dockerizePip: true

    # explicitly pass the arm64 platform to the docker build
    dockerImage: public.ecr.aws/sam/build-python3.11:latest-arm64

provider:
  name: aws
  runtime: python3.11
  region: eu-west-2
  memorySize: 128
  architecture: arm64
  timeout: 100

functions:
  api:
    handler: wsgi_handler.handler
    url: 
      cors: true
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements